mqtt:
  uri: "tcp://0.0.0.0:61613"
  username: "admin"
  password: "password"
  clientId: "SliwServer"
spring:
  data:
    elasticsearch:
      cluster-name: "elasticsearch"
      cluster-nodes: "127.0.0.1:9300"
